name: CI

on:
  pull_request: {}
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - name: test 
      run: ./gradlew clean shadowJar test jacocoTestReport
      working-directory: ./kotlin/local-data-api/
    - name: integration test
      run: |
        ./scripts/integration-test.sh 
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements-docs.txt
    - name: build document
      run: |
        cp README.md docs/index.md
        mkdocs build --verbose --clean --strict
